name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Configure npm for security
        run: |
          npm config set strict-ssl true
          npm audit --audit-level=high || exit 1
          npm audit fix --dry-run || exit 1

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format || exit 1

      - name: Run linting
        run: npm run lint || exit 1

      - name: Build Angular app (Production)
        run: npm run build -- --configuration=production --aot

      - name: Run unit tests with coverage
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
